import React from 'react';
import {StyleSheet} from 'react-native';
import {
  responsiveWidth,
  responsiveHeight,
  responsiveFontSize,
} from 'react-native-responsive-dimensions';
import {Colors} from 'react-native/Libraries/NewAppScreen';

const styles = StyleSheet.create({
  mainContainer: {
    backgroundColor: Colors.white,
  },
  container: {
    justifyContent: 'center',
  },

  contain: {
    height: responsiveHeight(90),
    width: '90%',
    alignSelf: 'center',
  },

  weleng: {
    color: '#006600',
    fontSize: 20,
    fontWeight: '500',
    textAlign: 'center',
  },

  welarb: {
    color: '#006600',
    fontSize: 20,
    fontWeight: '500',
    textAlign: 'center',
  },

  logeng: {
    color: '#006600',
    fontSize: 55,
    fontWeight: '500',
    textAlign: 'center',
    marginTop: responsiveHeight(3),
  },
  slogeng: {
    color: '#006600',
    fontSize: 12,
    fontWeight: '500',
    textAlign: 'center',
    marginTop: -10,
  },
  logarb: {
    color: '#006600',
    fontSize: 50,
    fontWeight: '500',
    textAlign: 'center',
    marginTop: -20,
  },
  slogarb: {
    color: '#006600',
    fontSize: 12,
    fontWeight: '500',
    textAlign: 'center',
    marginTop: 2,
  },
  enteng: {
    color: '#006600',
    fontSize: 9,
    fontWeight: '500',
    textAlign: 'center',
    marginTop: 80,
  },
  entarb: {
    color: '#006600',
    fontSize: 9,
    fontWeight: '500',
    textAlign: 'center',
    marginTop: 2,
  },
  VerifyAccount: {
    color: '#006600',
    fontSize: 18,
    fontWeight: 'bold',
    textAlign: 'center',
    marginTop: 40,
  },
  entercode: {
    color: '#006600',
    fontSize: 18,
    fontWeight: '500',
    textAlign: 'center',
    marginTop: 30,
  },
  codesent: {
    color: '#006600',
    fontSize: 18,
    fontWeight: '500',
    textAlign: 'center',
    marginTop: 0,
  },
  to: {
    color: '#006600',
    fontSize: 18,
    fontWeight: '500',
    textAlign: 'center',
    marginTop: 0,
    marginBottom: 0,
  },

  borderStyleBase: {
    width: 30,
    height: 45,
  },

  borderStyleHighLighted: {
    borderColor: '#7D9678',
  },

  underlineStyleBase: {
    width: 30,
    height: 45,
    borderWidth: 0,
    borderBottomWidth: 1,
    color: '#006600',
  },

  underlineStyleHighLighted: {
    borderColor: '#7D9678',
  },

  validcode: {
    color: '#006600',
    fontSize: 15,
    fontWeight: '500',
    textAlign: 'center',
    marginTop: 0,
  },
  resend: {
    color: '#5DC7D1',
    fontSize: 15,
    fontWeight: '600',
    textAlign: 'center',
    marginTop: 15,
    marginBottom: 15,
  },

  createpass: {
    color: '#006600',
    fontSize: 18,
    fontWeight: 'bold',
    textAlign: 'center',
    marginTop: 40,
    alignItems: 'center',
    justifyContent: 'center',
  },
  enterpass: {
    color: '#006600',
    fontSize: 18,
    fontWeight: '500',
    textAlign: 'center',
    marginTop: 30,
    alignItems: 'center',
    justifyContent: 'center',
  },
  youraccount: {
    color: '#006600',
    fontSize: 18,
    fontWeight: '500',
    textAlign: 'center',
    alignItems: 'center',
    justifyContent: 'center',
  },

  inputcpass: {
    width: 205,
    height: 45,
    borderRadius: 0,
    fontSize: 16,
    paddingLeft: 10,
    backgroundColor: 'transparent',
    color: '#7D9678',
    marginHorizontal: 15,
    marginTop: 10,
    marginBottom: 0,
  },

  terms: {
    color: '#7D9678',
    fontSize: 12,
    fontWeight: '500',

    marginTop: 10,
    marginBottom: 40,
  },
  signin: {
    color: '#006600',
    fontSize: 18,
    fontWeight: '500',
    textAlign: 'center',
    marginTop: 50,
    alignItems: 'center',
    justifyContent: 'center',
  },
  welback: {
    color: '#006600',
    fontSize: 20,
    fontWeight: 'bold',
    textAlign: 'center',
    marginTop: 30,
    marginBottom: 30,
    alignItems: 'center',
    justifyContent: 'center',
  },
  continue: {
    color: '#006600',
    fontSize: 16,
    fontWeight: '500',
    textAlign: 'center',
    marginTop: -10,
    alignItems: 'center',
    justifyContent: 'center',
  },

  inputsign: {
    width: 205,
    height: 45,
    borderRadius: 0,
    fontSize: 16,
    paddingLeft: 10,
    backgroundColor: 'transparent',
    color: '#7D9678',
    marginHorizontal: 15,
    marginTop: 30,
    marginBottom: 0,
  },
  forgot: {
    color: '#5DC7D1',
    fontSize: 15,
    fontWeight: '500',
    alignItems: 'center',
    justifyContent: 'center',
  },
  bobym: {
    color: '#5DC7D1',
    fontSize: 15,
    fontWeight: '500',
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: 25,
    marginTop: 100,
    marginBottom: 20,
  },
  logspace: {
    paddingTop: 100,
  },
  editprofile: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
  profileinput: {
    marginLeft: 22,
    fontSize: 18,
    padding: 8,
    margin: 10,
    color: '#006600',
    width: 300,
  },
  PhoneInput: {
    // marginLeft: 22,
    fontSize: 18,
    // padding: 8,
    marginTop: 0,
    marginLeft: 25,
    // margin: 10,
    color: '#006600',
    width: 300,
  },
  currentpass: {
    width: 315,
    height: 45,
    borderRadius: 0,
    fontSize: 16,
    paddingLeft: 10,
    backgroundColor: 'transparent',
    color: '#006600',
    marginHorizontal: 15,
    marginTop: 30,
    marginBottom: 0,
  },
  cnumber: {
    width: 205,
    height: 45,

    fontSize: 16,

    color: '#006600',
    marginLeft: 15,
    marginTop: 20,
  },
  chname: {
    width: 205,
    height: 45,

    fontSize: 16,

    color: '#006600',
    marginLeft: 15,
    marginTop: 20,
  },
  headerText: {
    padding: 8,
    fontSize: 14,
    color: '#444444',
    textAlign: 'center',
  },

  ed: {
    width: 205,
    height: 45,

    fontSize: 16,

    color: '#7D9678',
    marginLeft: 15,
    marginTop: 10,
  },
  cvv: {
    width: 205,
    height: 45,

    fontSize: 16,

    color: '#006600',
    marginLeft: 228,
    marginTop: -55,
  },
  newpass: {
    width: 315,
    height: 45,
    fontSize: 16,
    paddingLeft: 10,
    backgroundColor: 'transparent',
    color: '#006600',
    marginHorizontal: 15,
    marginTop: 20,
  },
  tabContent: {
    color: '#006600',
    fontSize: 18,
    margin: 24,
  },
  Seperator: {
    marginHorizontal: -10,
    alignSelf: 'stretch',
    borderTopWidth: 1,
    borderTopColor: '#888888',
    marginTop: 24,
  },
  tabStyle: {
    borderColor: '#D52C43',
  },
  activeTabStyle: {
    backgroundColor: '#D52C43',
  },
  scrollView: {
    backgroundColor: Colors.lighter,
  },
  ErrorView: {
    width: '79%',
    alignSelf: 'center',
    paddingVertical: responsiveHeight(0.5),
    justifyContent: 'center',
  },
  ErrorText: {
    color: 'red',
    fontSize: responsiveFontSize(1.6),
  },
  ContentContainer: {
    height: responsiveHeight(85),
    marginTop: responsiveHeight(2),
    width: '95%',
    alignSelf: 'center',
    backgroundColor: 'white',
    justifyContent: 'center',
    alignItems: 'center',
    // elevation: 5,
    borderRadius: 25,
  },
  TermsHeadingText: {
    color: 'black',
    fontWeight: 'bold',
    fontSize: responsiveFontSize(2.5),
    textTransform: 'uppercase',
  },
  textView: {
    marginTop: responsiveHeight(5),
    width: '80%',
    alignSelf: 'center',
  },
  contentText: {
    color: 'rgba(0,0,0,0.6)',
    fontSize: responsiveFontSize(1.9),
  },
  inputsStyles: {
    color: '#006600',
    borderRadius: 8,
    width: '100%',
    borderWidth: 1,
    borderColor: '#A6A6A6',
    paddingLeft: responsiveWidth(3),
    height: responsiveHeight(6),
    justifyContent: 'center',
  },
  inputView: {
    flexDirection: 'column',
    justifyContent: 'flex-end',
    alignSelf: 'center',
    width: '80%',
    height: responsiveHeight(8),
  },
  buttonTouch: {
    justifyContent: 'center',
    alignSelf: 'center',
    backgroundColor: '#006600',
    borderRadius: 10,
    width: '80%',
    height: responsiveHeight(7.5),
    marginVertical: responsiveHeight(3),
  },
  centeredView: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    marginTop: 22
  },
  completeView: {
    backgroundColor: '#006600',
    height: 60,
    alignItems: 'center',
    justifyContent: 'center',
    width: '80%',
    borderRadius: 5,
    marginHorizontal: '10%',
    marginTop: 20,
    marginBottom: 20
},
completeButton: {
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'center',
    color: '#fff', 
    fontSize: 24
},
  modalView: {
    margin: 20,
    backgroundColor: "white",
    borderRadius: 20,
    padding: 35,
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
  },
  button: {
    color: '#006600',
    borderRadius: 10,
    padding: 10,
    elevation: 2,
    margin: 5,
    width: 150,
    },
  buttonOpen: {
    backgroundColor: "#F194FF",
  },
  buttonClose: {
    backgroundColor: "#2196F3",
  },
  textStyle: {
    color: "white",
    fontWeight: "bold",
    textAlign: "center"
  },
  modalText: {
    marginBottom: 15,
    textAlign: "center"
  },
  selectProfile: {
    alignSelf: 'center',
  },
  uploadBar: {
   width: 100,
   backgroundColor: '#000',
   height: 30,
   opacity: 0.85,
   alignItems: 'center',
  },
  Header: {
    width: '100%',
    paddingVertical: responsiveHeight(1),
    flexDirection: 'row',
    justifyContent: 'space-between',
    backgroundColor: '#ffffff',
    alignItems: 'center',
  },
  headerTexts: {
    color: '#006600',
    fontWeight: '500',
    fontSize: responsiveFontSize(2.5),
  },
  HeadingTextView: {
    height: responsiveHeight(8),
    justifyContent: 'center',
    width: '80%',
    alignSelf: 'center',
  },
  ElevatedMapView: {
    width: '90%',
    height: responsiveHeight(30),
    alignSelf: 'center',
    paddingVertical: responsiveHeight(2),
    backgroundColor: 'white',
    elevation: 5,
    borderRadius: 15,
  },
  ScrollView: {
    flex: 1,
  },
  pic: {
    borderRadius: 10,
    width: responsiveWidth(6),
    height: responsiveHeight(3),
    resizeMode: 'contain',
  },
  pencilTouch: {
    position: 'absolute',
    top: responsiveHeight(12),
    right: responsiveWidth(38),
    width: responsiveHeight(5),
    height: responsiveHeight(5),
    borderRadius: responsiveHeight(5),
    backgroundColor: '#AAAAAA',
    justifyContent: 'center',
    alignItems: 'center',
  },
  profileImg: {
    backgroundColor: '#BDBDBD',
    width: responsiveHeight(15),
    height: responsiveHeight(15),
    borderRadius: responsiveHeight(15),
    alignSelf: 'center',
    marginTop: responsiveHeight(2),
  },
  ActivityView: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  IndicatorView:{
     flex:1,
     justifyContent: 'center',
     alignItems:'center',
     backgroundColor:'#fff'
  },
  NoItemsView: {
    flex: 1,
    alignItems: 'center',
    paddingTop: responsiveHeight(10),
    justifyContent: 'center',
  },
  NoItemsText: {
    color: 'black',
    fontSize: responsiveFontSize(3),
    fontWeight: 'bold',
  },
  icon: {
    flex: 1,
    width: 100,
    height: 50,
    backgroundColor: 'rgba(255, 255, 255, 1)',
    resizeMode: 'contain',
    position: 'absolute',
    left: 10
  },
  absoluteIcons:{
    position:'absolute',
    top:responsiveHeight(4.7),
    left:'5%',
    width: responsiveHeight(8),
    height: responsiveHeight(8),
    borderRadius: responsiveHeight(8),
  },
  usersinfo: {
    backgroundColor: '#dddd',
    width: responsiveHeight(45),
    height: responsiveHeight(35),
    borderRadius: responsiveHeight(8),
    alignSelf: 'center',
    marginTop: responsiveHeight(2),
  },
  userimg: {
    backgroundColor: '#BDBDBD',
    width: responsiveHeight(45),
    height: responsiveHeight(30),
    borderRadius: responsiveHeight(5),
    marginTop: responsiveHeight(1),
  },
  admintextView: {
    marginTop: responsiveHeight(1),
    width: '60%',
    alignSelf: 'center',
  },
  admininputsStyles: {
    borderRadius: 8,
    width: '100%',
   // borderWidth: 1,
    borderColor: '#A6A6A6',
    paddingLeft: responsiveWidth(1),
    height: responsiveHeight(3),
    justifyContent: 'center',
  },
   counttextView: {
    marginTop: responsiveHeight(1),
    width: '100%',
    alignSelf: 'center',
    backgroundColor: '#AEE6E6',
    justifyContent: 'center',
    fontSize:22,
    padding:10,
    textAlign:'center',
    borderWidth:responsiveHeight(0.05),
  },
   datePickerStyle: {
    backgroundColor:'#dddd',
    width: 200,
    marginTop: 10,
    justifyContent: 'center',
    alignSelf: 'center',
    borderWidth:0.3,
  },
  selectimg: {
    width: responsiveHeight(38),
    height: responsiveHeight(15),
    borderRadius: responsiveHeight(1),
    alignSelf: 'center',
    marginTop: responsiveHeight(2),
    borderWidth:0.5,
  },
   selectimge: {
    width: responsiveHeight(38),
    height: responsiveHeight(15),
    borderRadius: responsiveHeight(1),
    alignSelf: 'center',
    marginTop: responsiveHeight(2),
    borderWidth:0,
  },
});
export default styles;